version: "3"
services:
  backend:
    build:
      context: ./packages/backend
      args:
        NODE_ENV: development # 개발 환경일 경우 development, 배포 환경일 경우 production
    environment:
      NODE_ENV: development # 개발 환경일 경우 development, 배포 환경일 경우 production
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    ports:
      - "21572:21572"
    env_file: .env

  frontend:
    build:
      context: ./packages/frontend
      args:
        NODE_ENV: development # 개발 환경일 경우 development, 배포 환경일 경우 production
    environment:
      NODE_ENV: development # 개발 환경일 경우 development, 배포 환경일 경우 production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "20064:20064"
    env_file: .env
