version: "3.8"
services:
  backend:
    build:
      context: ./packages/backend
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    volumes:
      - .:/app # 루트 디렉토리를 마운트하여 hot reloading 적용
      - /app/node_modules # node_modules는 마운트하지 않음
    working_dir: /app/packages/backend
    ports:
      - "8000:3000" # 외부에서 21572 포트로 접근, 내부는 3000 포트로 동작
    networks:
      - kaitly_network
    env_file: .env
    command: pnpm run start:dev # dev 모드 실행

  frontend:
    build:
      context: ./packages/frontend
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    volumes:
      - .:/app # 루트 디렉토리를 마운트하여 hot reloading 적용
      - /app/node_modules # node_modules는 마운트하지 않음
    working_dir: /app/packages/frontend
    ports:
      - "3000:3000" # 외부에서 20064 포트로 접근, 내부는 3000 포트로 동작 (Next.js 기본 포트)
    networks:
      - kaitly_network
    env_file: .env
    command: pnpm run dev # next.js dev 모드 실행

networks:
  kaitly_network:
    driver: bridge
