version: "3.8"
services:
  backend:
    environment:
      NODE_ENV: production # 배포 환경일 경우 production
    networks:
      - kaitly_network

  frontend:
    environment:
      NODE_ENV: production # 배포 환경일 경우 production
    networks:
      - kaitly_network
