version: "3.8"
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} # 환경 변수에서 MySQL 비밀번호 가져오기
      MYSQL_DATABASE: ${DB_DATABASE} # 환경 변수에서 MySQL DB 이름 가져오기
    ports:
      - "3306:3306" # 기본 MySQL 포트
    volumes:
      - mysql_data:/var/lib/mysql # MySQL 데이터 저장 볼륨
    networks:
      - kaitly_network # 이미 정의된 네트워크를 참조

volumes:
  mysql_data: # MySQL 데이터가 저장될 볼륨

networks:
  kaitly_network:
    external: true # 이미 바닐라 docker-compose.yml에서 정의된 네트워크를 참조
